# Generated by Django 5.2 on 2025-07-07 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.basemodel')),
                ('emp_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(choices=[('frontend_developer', 'frontend_developer'), ('backend_developer', 'backend_developer'), ('fullstack_devloper', 'fullstack_devloper')], max_length=25)),
                ('emp_datajoing', models.DateField()),
                ('emp_project', models.CharField(max_length=49)),
            ],
            bases=('employees.basemodel',),
        ),
    ]
