# Generated by Django 5.2 on 2025-07-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('client_name', models.CharField(max_length=100)),
            ],
            bases=('employees.basemodel',),
        ),
        migrations.AlterField(
            model_name='employemodel',
            name='emp_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.project'),
        ),
    ]
