# Generated by Django 5.2 on 2025-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_project_alter_employemodel_emp_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_name',
            new_name='pro_client_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='pro_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='pro_start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='pro_designation',
            field=models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('designer', 'Designer')], default='Developer', max_length=25),
        ),
    ]
