FRONTEND_DEVELOPER = "frontend_developer"
BACKEND_DEVELOPER = "backend_developer"
FULLSTACK_DEVELOPER = "fullstack_devloper"

STREAM_CHOICES = (
    (FRONTEND_DEVELOPER, FRONTEND_DEVELOPER),
    (BACKEND_DEVELOPER, BACKEND_DEVELOPER),
    (FULLSTACK_DEVELOPER, FULLSTACK_DEVELOPER)
)

STREAM_CHOICES = [
    ('DEV', 'Developer'),
    ('QA', 'Quality Analyst'),
]